# Generated by Django 2.2.6 on 2019-11-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cocina', '0002_auto_20191117_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('administrador', 'Es administrador'), ('usuario', 'Es usuario'))},
        ),
    ]
